:toc:
:toc-placement:
:sectnums: |,all|
toc::[]

Option A is the best solution and well explain.
Option D it will work, but the error.errorType will not complain with the expected error.errorType (namescace MULE / identifier UNKNOWN), and it will need a few extra steps to not show as error in the Mule Configuration Files.

The base for all of the options is to enable the flow in each munit test

In case you find something like this error:

====
[source,bash,lineenums]
----
org.mule.munit.runner.model.TestExecutionException: Error [MULE:UNKNOWN] while running test 'test-test-suite-test-dynamic-FlowTest':Invalid flow name: 'munit-set-error-code-event-flow'. HINT: only flows can be used, not sub-flows
	at org.mule.munit.runner.flow.TestFlow.run(TestFlow.java:320)
	at org.mule.munit.runner.model.Test.run(Test.java:98)
	at org.mule.munit.runner.model.Suite.run(Suite.java:112)
----
====

== Option A

This example shows how to test HTTP error in Mule 4 with Munit 2.

If you encounter this issue

```bash
org.mule.runtime.api.exception.MuleRuntimeException: org.mule.runtime.core.api.config.ConfigurationException: [option-a/implementation-test-suite.xml:42]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.listener-flow' must be one of stereotypes [MULE:FLOW, MULE:SUB_FLOW].
[option-a/implementation-test-suite.xml:114]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be one of stereotypes [MULE:FLOW].
[option-a/implementation-test-suite.xml:188]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
[option-a/implementation-test-suite.xml:218]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
Caused by: org.mule.runtime.core.api.config.ConfigurationException: [option-a/implementation-test-suite.xml:42]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.listener-flow' must be one of stereotypes [MULE:FLOW, MULE:SUB_FLOW].
[option-a/implementation-test-suite.xml:114]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be one of stereotypes [MULE:FLOW].
[option-a/implementation-test-suite.xml:188]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
[option-a/implementation-test-suite.xml:218]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist


WARN  2025-09-26 15:41:01,116 [munit.01] org.mule.runtime.config.internal.context.MuleArtifactContext: [option-a/implementation-test-suite.xml:117]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be one of stereotypes [MULE:FLOW].
org.mule.runtime.api.exception.MuleRuntimeException: org.mule.runtime.core.api.config.ConfigurationException: [option-a/implementation-test-suite.xml:117]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be one of stereotypes [MULE:FLOW].
[option-a/implementation-test-suite.xml:191]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
[option-a/implementation-test-suite.xml:221]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
Caused by: org.mule.runtime.core.api.config.ConfigurationException: [option-a/implementation-test-suite.xml:117]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be one of stereotypes [MULE:FLOW].
[option-a/implementation-test-suite.xml:191]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
[option-a/implementation-test-suite.xml:221]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
```

It's important to enable the flows that will be used in the test

```xml
    <munit:enable-flow-sources>
      <munit:enable-flow-source
        value="munit-util-mock-http-error-with-errorMessage-test-suite.listener-flow" />
      <munit:enable-flow-source
        value="munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow" />
    </munit:enable-flow-sources>
```

If this error persist in some way, you may move the flows from one file to the same where the munit test, but in this case you will need to concentrate all munit tests in one test suite only.

You may think in Import the other file, but this doesn't work his is a Bug and you will need to Import the file that has the flows for the Request and Listener:

```xml
<import
    doc:name="Import"
    file="option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml"
    doc:description="munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml" />
````

When Running in Studio or using maven `mvn clean test` you will need to comment or remove the `import`, otherwise will get an error like:

```bash
org.mule.runtime.api.exception.MuleRuntimeException: org.mule.runtime.core.api.config.ConfigurationException: [option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:27; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:27]: Two (or more) configuration elements have been defined with the same global name. Global name 'MUnit_HTTP_Listener_config' must be unique.
[option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:36; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:36]: Two (or more) configuration elements have been defined with the same global name. Global name 'MUnit_HTTP_Request_configuration' must be unique.
[option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:43; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:43]: Two (or more) configuration elements have been defined with the same global name. Global name 'munit-util-mock-http-error-with-errorMessage-test-suite.listener-flow' must be unique.
[option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:67; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:67]: Two (or more) configuration elements have been defined with the same global name. Global name 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be unique.
Caused by: org.mule.runtime.core.api.config.ConfigurationException: [option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:27; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:27]: Two (or more) configuration elements have been defined with the same global name. Global name 'MUnit_HTTP_Listener_config' must be unique.
[option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:36; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:36]: Two (or more) configuration elements have been defined with the same global name. Global name 'MUnit_HTTP_Request_configuration' must be unique.
[option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:43; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:43]: Two (or more) configuration elements have been defined with the same global name. Global name 'munit-util-mock-http-error-with-errorMessage-test-suite.listener-flow' must be unique.
[option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:67; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:67]: Two (or more) configuration elements have been defined with the same global name. Global name 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be unique.
INFO  2025-09-26 14:40:26,253 [munit.01] org.mule.munit.runner.remote.api.server.RunnerServer: Waiting for client connection
```

So, you could leave the file in `src/main/mule`, but it's important to


=== Dynamic Port

This approach use the dynamic port feature from MUnit

https://docs.mulesoft.com/munit/latest/dynamic-ports




== Option B

A simple flow and munit test similar to the option B, but in this case the HTTP Listener is in a flow inside  is on `src/main/`

Original source code: link:https://help.salesforce.com/s/articleView?id=001117133&type=1[How to test HTTP error in Mule 4 with Munit 2]

In this option is important to consider move the flow for HTTP Listener from `munitusage.xml` in the directory `src\main\mule\option-b` so the flow and the respective configuration goes to `src/test/munit/option-b`.
This avoid any invalid usage or even the deploy on Mule Runtime.

You may add to your `pom.xml` file to ignore the file in the build:

```xml
    <build>
        <plugins>
            <plugin>
                <!-- INFO: This plugin is not intended to be used like this, but it works. You may need to find another solution and test if it works. -->
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <delete file="${project.build.outputDirectory}/option-b/munitusage.xml" />
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

== Option C

https://wearecommunity.io/communities/integration/articles/1618


== Option D

- not the best option, because the errorType returns MULE:UNKNOWN
- 

https://stackoverflow.com/questions/71778157/how-to-raise-a-custom-error-with-internal-payload-error-errormessage-payload-i

when you find the issue below:

You probably will have 

====
[source,bash,lineenums]
----
org.mule.runtime.api.exception.MuleRuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'munit-set-error-code-event-flow': Cannot create inner bean '(inner bean)#4a329eca' of type [org.mule.munit.runner.processors.SetEventProcessor] while setting bean property 'messageProcessors' with key [1]; nested exception is Error creating bean with name '(inner bean)#4a329eca': Failed properties: Failed to convert property value of type 'org.mule.munit.common.api.model.UntypedEventError' to required type 'org.mule.munit.common.api.model.UntypedEventError' for property 'error'; class java.lang.String cannot be cast to class java.lang.Throwable (java.lang.String and java.lang.Throwable are in module java.base of loader 'bootstrap'); nested exception is Failed properties: Failed to convert property value of type 'org.mule.munit.common.api.model.UntypedEventError' to required type 'org.mule.munit.common.api.model.UntypedEventError' for property 'error'; class java.lang.String cannot be cast to class java.lang.Throwable (java.lang.String and java.lang.Throwable are in module java.base of loader 'bootstrap')
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'munit-set-error-code-event-flow': Cannot create inner bean '(inner bean)#4a329eca' of type [org.mule.munit.runner.processors.SetEventProcessor] while setting bean property 'messageProcessors' with key [1]; nested exception is Error creating bean with name '(inner bean)#4a329eca': Failed properties: Failed to convert property value of type 'org.mule.munit.common.api.model.UntypedEventError' to required type 'org.mule.munit.common.api.model.UntypedEventError' for property 'error'; class java.lang.String cannot be cast to class java.lang.Throwable (java.lang.String and java.lang.Throwable are in module java.base of loader 'bootstrap'); nested exception is Failed properties: Failed to convert property value of type 'org.mule.munit.common.api.model.UntypedEventError' to required type 'org.mule.munit.common.api.model.UntypedEventError' for property 'error'; class java.lang.String cannot be cast to class java.lang.Throwable (java.lang.String and java.lang.Throwable are in module java.base of loader 'bootstrap')
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'error_handlingSub_FlowTest': Cannot create inner bean '(inner bean)#2babdabc' of type [org.mule.munit.runner.component.factory.TestProcessorChainFactory_ByteBuddy_org_mule_runtime_core_privileged_processor_chain_MessageProcessorChain] while setting bean property 'processorChains' with key [0]
----
====

This is probably related to the MUnit Maven Plugin

Revise the version, it's being know that version `3.4.0` it has this issue for example. You can confirm by executing only `test/munit/option-d/docs-mule-set-event-with-error-test-suite.xml` to validate the same usage of attribute `exception` to thrown an error.